module RingCentralSdk::REST
  autoload :Cache, 'ringcentral_sdk/rest/cache'
  autoload :Client, 'ringcentral_sdk/rest/client'
  autoload :Config, 'ringcentral_sdk/rest/config'
  autoload :ConfigApp, 'ringcentral_sdk/rest/config'
  autoload :ConfigUser, 'ringcentral_sdk/rest/config'
  autoload :ConfigEnvRc, 'ringcentral_sdk/rest/config'
  autoload :Extension, 'ringcentral_sdk/rest/extension'
  autoload :ExtensionPresence, 'ringcentral_sdk/rest/extension_presence'
  autoload :Messages, 'ringcentral_sdk/rest/messages'
  autoload :MessagesFax, 'ringcentral_sdk/rest/messages'
  autoload :MessagesSMS, 'ringcentral_sdk/rest/messages'
  autoload :Request, 'ringcentral_sdk/rest/request'
  autoload :Subscription, 'ringcentral_sdk/rest/subscription'
end